services:

  gitea:
    image: gitea/gitea:latest
    container_name: gitstack-gitea
    restart: always
    ports:
      - "3002:3000"
      - "2222:22"
    volumes:
      - gitstack_gitea_data:/data

  postgres:
    image: postgres:17.6-alpine
    container_name: gitstack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gitstack
      POSTGRES_USER: gitstack
      POSTGRES_PASSWORD: gitstack_dev_password
    ports:
      - "5432:5432"
    volumes:
      - gitstack_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitstack -d gitstack"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  gitstack_gitea_data:
  gitstack_postgres_data:


networks:
  gitstack_sandbox_network:
    name: gitstack-sandbox-network
    driver: bridge
    internal: true